version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        extra_hosts:
            - "ams.local:127.0.0.1"
        hostname: ams.local
        domainname: local
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
        networks:
            - ams_site

    php:
        container_name: php
        build:
            context: ./etc/php
        ports:
            - '9000:9000'
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
        depends_on:
            - mysqldb
        networks:
            - ams_site

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
        networks:
            - ams_site

    mysqldb:
        image: mysql
        platform: linux/arm64
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            # - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - "./etc/nginx/mysql:/docker-entrypoint-initdb.d"
            - "./etc/mysql:/var/lib/mysql"
        networks:
            - ams_site

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - ./etc/rabbitmq:/var/lib/rabbitmq
        networks:
            - ams_site

    mailhog:
        image: mailhog/mailhog
        container_name: 'mailhog'
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - ams_site

networks:
    ams_site: